### ISSUE TITLE
Support for multiple elements in the same instance

### ISSUE THREAD

**Issue by Jakkc** [ndelvalle/v-click-outside#15]
Currently just triggers for everything.

Would be nice if I could attach it to each item in a rendered list and then be able to interact with each one individually

**Comment by francois2metz** [comment]
Hi @Jakkc. It already support multiple instance since the version 0.1. 

If not, could you provide a testcase please?

**Comment by Jakkc** [comment]
Attaching the event dynamically to items generated from a v-for loop.

I overcame this problem by creating a separate component with its own instance of click-outside.

However I did then notice a bug whereby if I clicked on one of the components and then a second without triggering click-outside then the click-outside event detached itself from both components.

It seems that v-clickaway doesn't have this issue.

I will try and provide an example later.

**Comment by francois2metz** [comment]
@Jakkc Any news?

**Comment by francois2metz** [comment]
Closing without any more info. Feel free to reopen if you have some news.
