### ISSUE TITLE
Touch and click events are not recognized correctly 

### ISSUE THREAD

**Issue by ppasieka** [ndelvalle/v-click-outside#19]
I have laptop with touch screen, but for 99% of my usage time I'm using mouse and rely on click event. After update to v1.0.1 my app is broken because plugin recognize that I have touch screen and only registers touchstart events.

**Comment by ndelvalle** [comment]
Thanks for reporting the issue @ppasieka I will investigate and try to fix it these days (I'm a bit busy with university finals). It's going to be hard to test it since I don't have a laptop with touchscreen, but I can release a beta for you to test it 🙂

**Comment by ndelvalle** [comment]
v-click-outside 1.0.2 published 🎉 @ppasieka
