### ISSUE TITLE
Why update is needed?

### ISSUE THREAD

**Issue by Cxz-web** [ndelvalle/v-click-outside#209]

**Comment by ndelvalle** [comment]
@Cxz-web the update is needed when a config object is used. Example:
```
vcoConfig: {
        handler: this.handler,
        middleware: this.middleware,
        events: ['dblclick', 'click'],
        // Note: The default value is true, but in case you want to activate / deactivate
        //       this directive dynamically use this attribute.
        isActive: true
      }
```

So the idea is that if the user updates one of these attributes we run the update function using the new attributes.
Does this answer your question?

**Comment by ndelvalle** [comment]
@Cxz-web feel free to reopen the issue if my answer did not help you.
