### ISSUE TITLE
The judgment event.target !== el is superfluous

### ISSUE THREAD

**Issue by baooab** [ndelvalle/v-click-outside#211]
I think the 34th line in the source code is superfluous.

```javascript
const isClickOutside = event.target !== el && outsideCheck
```

Because when `outsideCheck` is `true`, `event.target! == el` must be `true`. 

Therefore it should be written as：

```diff
- const outsideCheck = path ? path.indexOf(el) < 0 : !el.contains(event.target)
- const isClickOutside = event.target !== el && outsideCheck
+ const isClickOutside = path ? path.indexOf(el) < 0 : !el.contains(event.target)
```

Is not it?

**Comment by ndelvalle** [comment]
@baooab I am not 100% sure if we are covered in all cases. Do you mean that if `outsideCheck` is true, the `event.target` is always different than the `el`?
If you are sure about it, feel free to create a PR, I'll take a look a test it locally, It would be nice to have tests to make sure about this :/

**Comment by baooab** [comment]
> Do you mean that if `outsideCheck` is true, the `event.target` is always different than the `el`?

Yes, it is. I have tested and submitted a PR~ https://github.com/ndelvalle/v-click-outside/pull/212
