### ISSUE TITLE
v-click-outside with overlap does not close with two components

### ISSUE THREAD

**Issue by dxc-jbeck** [ndelvalle/v-click-outside#214]
We have 2 VueJs components with overlapping divs.  They are menu drop down boxes.  
1) Click on the first component (blue) to open 
2) Click on the yellow part to open green

Expected:  blue will close
Actual: blue stays open (because both are using v-click-outside)

![v-click-once-overlap](https://user-images.githubusercontent.com/54046008/86008133-5ea96d80-b9e6-11ea-9ad2-3dcb156fde92.png)

**Comment by PierreMaraisZA** [comment]
what was the fix here

**Comment by yoshrubin** [comment]
@dxc-jbeck how were you able to solve this? I am running into the same issue

**Comment by yoshrubin** [comment]
ok so I solved this.
The issue I had was that I had a `@click.stop` on a parent element removing that didn't help at first but then figuring out why I needed the `.stop` at first I found the source of my issue

so if anyone runs into this issue in the future look for any other clicks that may interfere
