### ISSUE TITLE
Integration in Nuxt.js

### ISSUE THREAD

**Issue by Frederick-88** [ndelvalle/v-click-outside#219]
Good day! Thanks for making such a great plugin =) , currently i want to integrate it in Nuxt and maybe its better if there are docs about it so Nuxt Developers also could put in "v-click-outside" inside their development.

**Comment by christopher4lis** [comment]
You figure out a way to integrate this globally?

**Comment by gauravmak** [comment]
https://dpatelierdigital.com/en/articles/detect-external-click/
