### ISSUE TITLE
Clicking sibling item does not hide original

### ISSUE THREAD

**Issue by syropian** [ndelvalle/v-click-outside#25]
I have a list of tags in a sidebar, and when I click the `...` to open it, clicking another `...` in the list does not hide the first one. Attatched a GIF for reference since it's a little confusing 😅 

![astral_click_outside_bug](https://user-images.githubusercontent.com/749061/37877307-3ce14f06-3027-11e8-80da-e5a8c49a72fd.gif)

**Comment by francois2metz** [comment]
Hi! Could you provide a snippet of the code so we can reproduce it?

**Comment by syropian** [comment]
@francois2metz Hi! I created a simple reproduction of the issue here - https://codesandbox.io/s/wq8olo9yq7

To see it, click the `...` on one item, and then click the `...` on another item. You'll notice that both menu items show, and neither hide until you click somewhere else.

**Comment by francois2metz** [comment]
Hi @syropian. You are stopping the click event on the button, so the plugin cannot handle the event when clicking on another button. You should remove the `stop` modifier and move ` v-click-outside` to the div that encompass the button and the context menu. Here is the version working: https://codesandbox.io/s/wnp565o56l (I also move the v-show from the context-menu to the fruit component, it was easier for me).

**Comment by syropian** [comment]
Thanks for taking a look. The issue which I realized I failed to demonstrate in that example is I need to stop the propagation because in my app I’m also handling a click event on the whole row as well, and I don’t want to trigger the row’s click event when clicking the `...`

**Comment by francois2metz** [comment]
I see. It's difficult then to handle click outside of the event.

**Comment by adamreisnz** [comment]
@syropian ever found a solution that didn't involve having to actively manage the visibility state of each sibling?

**Comment by syropian** [comment]
@adamreisnz Keep in mind this is pretty old code now, but I _think_ the solution was wrapping the button in a div like so — https://github.com/astralapp/astral/blob/master/resources/assets/js/components/Dashboard/Sidebar/SidebarTag.vue#L17-L32

In a newer version I have it all working automatically by using [HeadlessUI](https://headlessui.dev/)
