### ISSUE TITLE
Event are not recognized on mobile devices

### ISSUE THREAD

**Issue by LiamKlyneker** [ndelvalle/v-click-outside#26]
Exist a special call for mobile devices?

**Comment by LiamKlyneker** [comment]
**I found the solution**!!! 🙌

If the v-click-outside is not firing on iOS, try adding the cursor: pointer css style to the <body> element. There are many ways to achieve this, after I did this, v-click-outside started working like a charm.

**Comment by ndelvalle** [comment]
Cool, thanks for sharing the solution @LiamKlyneker 🙂

**Comment by brendon** [comment]
This is a bit of a usability problem since now the mouse looks like a pointer all of the time :(
