### ISSUE TITLE
typo in test description

### ISSUE THREAD

**Issue by kris-luminar** [ndelvalle/v-click-outside#28]
This line says `'does not execute the callback if the event target its the element from the instance'`

https://github.com/ndelvalle/v-click-outside/blob/master/test/v-click-outside.test.js#L116

It's unclear what `its the element` means. Did you mean `its element`?

**Comment by ndelvalle** [comment]
@kris-luminar  I mean the element you are using the directive on. Maybe it should say:
`It does not execute the callback if the event target is the element from the directive instance`?
To be more clear it should only call the `cb` if the element is not the one we are using the directive on and does not contains the event target. What do you think?

**Comment by kris-luminar** [comment]
> It does not execute the callback if the event target is the element from the directive instance

That's a lot clearer to me.

**Comment by ndelvalle** [comment]
Cool, @kris-luminar do you mind doing a PR changing it? 🙂
