### ISSUE TITLE
fontawesome icon get trick as outside click

### ISSUE THREAD

**Issue by lkloon123** [ndelvalle/v-click-outside#31]
```
<template>
<div v-click-outside="submitForm">
    <button class="btn btn-box-tool btn-edit" title="Click to add name" @click="submitForm">
        <i class="fa fa-plus-circle"></i>
    </button>
</div>
</template>
```

submitForm will be trigger twice due to clicking on the fontawesome circle icon,
but if i click on the button, it has no issue

**Comment by ndelvalle** [comment]
Hi @lkloon123  Using version 2 you can define a middleware function to check if the click was on the fa icon and avoid the execution of the callback.
If you create a [codesanbox](https://codesandbox.io/) I can help you implement it, or I can debug the problem for you.

**Comment by ndelvalle** [comment]
@ilearnio I'm going to close this due to inactivity.
