### ISSUE TITLE
outside-if-not functionality 

### ISSUE THREAD

**Issue by willashley23** [ndelvalle/v-click-outside#32]
It would be nice if the directive could check for a attribute `outside-if-not` which excludes certain selectors when determining if the user has clicked outside. This is useful for cases when you are layering multiple elements, such as a modal over a side panel. 

You could add the selectors to be excluded as an array inside the `directive` object, and check for them here: 

```javascript
if (event.target !== el && !el.contains(event.target)) {
      fn && fn(event)
}
```
It would be cleaner to use a clause, but that would be a breaking change. I'd be happy to open a PR for this!

**Comment by ndelvalle** [comment]
I think this change would be useful @willashley23 , I'm not entirely sure about the implementation. Maybe we can add an extra option to the directive, to be a function where we pass the element and the user do something and return true if we should execute the associated binding.value function, something like:

```js
if (event.target !== el && !el.contains(event.target) && userFn(el, event)) {
      fn && fn(event)
}
```

This way is more dynamic I think.
Im not sure if we should add that function in the binding value or as a modifier (I think I like the first option better)
Something like this:
```js
const onClick = () => console.log('clicked')
const shouldClick = (el, event) => el.className !== 'modal'
<div v-click-outside="{ onClick, middleware: shouldClick }"></div>
```

Let me know what you think.

**Comment by willashley23** [comment]
I like it! I think it is more maintainable and generic so people can enable or prevent the directive callback based on whatever their specific needs are as described in the middleware. I'll implement this, add tests, and send over a pr 😄

**Comment by ndelvalle** [comment]
Awesome! Thanks for contributing @willashley23 🙌🏻

**Comment by ndelvalle** [comment]
v-click-outside 2.0.0-0 published with these changes, I will do some testing and the publish a final release (Not beta)
