### ISSUE TITLE
Error: "Binding value must be a function or an object"

### ISSUE THREAD

**Issue by TheMangoTrain** [ndelvalle/v-click-outside#321]
Hey,

Just a heads up...

**1. FAILS:**
`<div v-click-outside="closeMenu()">`

Error: "Binding value must be a function or an object"

**2. WORKS:**
`<div v-click-outside="closeMenu">`

Simply removing the brackets makes it work.

In my Vue component, `closeMenu()` is a method, and methods _are_ functions, so the first example above should work. In Vue-land, some people use brackets for methods in a template, some not. Personally I always include brackets on my methods in templates because it helps to discern them from prop's, computed's and other attributes. And even better, IDE's actually color code methods differently when you add the brackets.

**SUGGESTION:**
Make this plugin process methods with-or-without brackets.

... or if there's a good reason to not do this, at least have the docs explicitly state template methods should not include brackets.

---

For reference, the method is below:
```
    methods: {
        closeMenu() {
            console.log("Hello!")
        }
    }
```

**Comment by andyfensham** [comment]
I also need it as I need to pass a parameter to my function like
`v-click-outside="update({ modalOpen: true })"`

**Comment by ndelvalle** [comment]
> I also need it as I need to pass a parameter to my function like
> `v-click-outside="update({ modalOpen: true })"`

@andyfensham did you try 

```html
v-click-outside="() => update({ modalOpen: true })"

```
