### ISSUE TITLE
Bad generated files (.min.min)

### ISSUE THREAD

**Issue by Finrod927** [ndelvalle/v-click-outside#36]
Hi ndelvalle!

I just upgraded to 2.0.0 and my build failed with a "dependency not found error". I checked the package in node_modules and the files for **v-click-outside** are badly named in `dist` folder:

- `v-click-outside.min.min.umd.js`
- `v-click-outside.min.min.umd.js.map`

The `package.json` is targetting `v-click-outside.min.umd.js`

**Comment by ndelvalle** [comment]
@Finrod927 I pushed a new npm version! I will create a new github release once I solve the issue 👍 
Related: https://github.com/developit/microbundle/issues/205

Thanks for reporting

**Comment by Finrod927** [comment]
Great, thanks for the quick fix!

When you create a github release, can you post a small note to sum up the changes ?
I had to look at the commits to see what was new on 2.0.0 and if there was a breaking change.
Thanks ;)

**Comment by ndelvalle** [comment]
Here goes: [Docs](https://github.com/ndelvalle/v-click-outside/blob/master/README.md#migrate-from-version-1)
