### ISSUE TITLE
Detecting type of touch event

### ISSUE THREAD

**Issue by paulrosen** [ndelvalle/v-click-outside#37]
It looks like, when the function is triggered on a touch screen, it is only triggered on "touchstart". I would like to detect whether the user did a simple tap of the screen or did a scroll motion, but it doesn't look like I can tell.

**Comment by ndelvalle** [comment]
@paulrosen on the callback argument you have the `event` attribute, you can get the event type like:
```js
function onClickOurside(event, el) {
  console.log(event.type) // 'click'
}
```

Will this work for you?

**Comment by paulrosen** [comment]
That works halfway - I can tell if it was a mouse click or a touch event, but I'm trying to determine what *kind* of touch event it is. That was going to be my workaround, where I ignore all touch events.

In other words, if the user taps, I want to do something. If the user swipes, I do not. But in both of those cases event.type === "touchstart".

And thanks for the library - it's been very useful!

**Comment by ndelvalle** [comment]
@paulrosen I see, it's a very specific case, I'm thinking 2 possibilities:

1) We can change the middleware behavior so it works asynchronously and then, inside of the middleware check if the user is swiping the screen, and then based on that return true or false, to call the desired on click outside callback. This will require to change the current API, and make breaking changes.

2) This is a bit tricky, but I think it will work. Subscribe to `['click', 'touchstart', 'touchmove']` so, if you touch or if you swipe the callback will be fired.
Then use this [nice library](https://github.com/autonomoussoftware/time-bombs) to do something like this:

```js
const timer = 100
let bomb = null

function doSomething() {
  // Here will be the actual click outside cb logic
}

function onClickOutside (event) {
  if (event.type === 'touchstart') {
      bomb = timeBombs.create(timer, doSomething)
  } else if (event.type === 'touchmove' && bomb) {
    // This will deactivate the bomb, so 
    bomb.deactivate()
  } else {
    doSomething()
  }
}
```

So the idea behind this is to only call the `doSomething` function if there is a `click`, or a `touchstart` without a `touchmove` in a determined (timer variable) amount of time.


I know both solutions are not straightforward, maybe we can add more logic to the directive to handle all this. I just can't think of any nice way to do right now. What do you think @paulrosen

**Comment by paulrosen** [comment]
Well, you gave me a clue with the hint to subscribe to only some events. I was using the simple form of `v-click-outside="myHandler"` instead of using a config object. I somehow missed that way to set it up. I figured out that on touch devices, I get a "click" event as a second event, so I just needed to subscribe to "click" and it works everywhere. 

Thanks for your quick replies!

My full code is:

```
...
<div v-click-outside="vcoConfig">
...
<script>
  import vClickOutside from 'v-click-outside'
  export default {
    data() {
      return {
        vcoConfig: {
          handler: this.onClickOutside,
          events: [ 'click']
        },
    };
  },
  directives: {
    clickOutside: vClickOutside.directive
  },
  methods: {
    onClickOutside() {
      this.$emit('close');
    }
  }
};
...
```

**Comment by ndelvalle** [comment]
Awesome, thanks for sharing the solution @paulrosen 👍
