### ISSUE TITLE
window is not defined in nuxt

### ISSUE THREAD

**Issue by guanzo** [ndelvalle/v-click-outside#39]
I'm using `nuxt` 2.3.4 and `v-click-outside` 2.0.1

Here's the error: https://i.gyazo.com/8ac67cb87dbf966efc229f6fa7b7776a.png

**Comment by ndelvalle** [comment]
@guanzo I'm not entirely sure how nuxt works, but is there a way to disable the use of this directive on the server?
If that is not possible I might default window to an empty object or something like that, but then the logic to recognize touch devices will not work as expected.

**Comment by guanzo** [comment]
Here's some official tips for writing SSR compatible code: https://ssr.vuejs.org/guide/universal.html#component-lifecycle-hooks

The way you conditionally export the package should work:
https://github.com/ndelvalle/v-click-outside/blob/df13e58ca873738eafebc472474de0c7d046339b/lib/v-click-outside.js#L78

However - and I'm surprised no one else has complained about this - you nullify that condition by directly accessing `window` and `navigator` at line 1, which are browser only globals:
https://github.com/ndelvalle/v-click-outside/blob/df13e58ca873738eafebc472474de0c7d046339b/lib/v-click-outside.js#L1

Module code is executed when the module is imported, so you need somehow prevent JS from accessing `window` and `navigator`.  You can hide them behind conditionals, like 

```
 const isTouch = (typeof window !== 'undefined') && ('ontouchstart' in window || navigator.msMaxTouchPoints > 0)
```
Or you can take `window` and `navigator` out of the global scope and access them in functions.

The goal is for the `v-click-outside` module to be importable during SSR without throwing any errors. I can try a pull request if helpful.
