### ISSUE TITLE
Problem when use any element in `div outside`

### ISSUE THREAD

**Issue by thearabbit** [ndelvalle/v-click-outside#4]
my code 
```js
<div v-click-outside="onClickOutside">
       <el-button type="danger" @click="remove">Del</el-button>
</div>
------
onClickOutside (event) {
     console.log('outside');
}
```
When I click `button` , `onClickOutside method` work too.
Should be don't work because `button` is it `onClickOutside`

**Comment by monishnarwani** [comment]
change to this to stop propagating events
<div v-click-outside="onClickOutside">
       <el-button type="danger" @click.stop="remove">Del</el-button>
</div>
------
onClickOutside (event) {
     console.log('outside');
}

hope this helps you.:)

**Comment by ndelvalle** [comment]
@thearabbit I could not reproduce the error, can you provide a jsbin or let me know if you found a solution?

**Comment by thearabbit** [comment]
sorry, Now I use `vue-outside-events` instead.
