### ISSUE TITLE
Multiple triggering (v 2.1.1)

### ISSUE THREAD

**Issue by dariusFromShire** [ndelvalle/v-click-outside#72]
Multiple method calls per click.

![image](https://user-images.githubusercontent.com/46776262/57127996-baed0f00-6d9a-11e9-9b8f-c731a6890ff4.png)

Version 2.0.2 - Ok.

**Comment by ndelvalle** [comment]
v-click-outside 2.1.2 published 🎉

**Comment by ndelvalle** [comment]
@dariusFromShire I'm not sure what you mean, in the case you are testing it seems ok to fire 2 callbacks because you are clicking outside those 2 elements.
