### ISSUE TITLE
Old package in npm

### ISSUE THREAD

**Issue by ThD-Rizer** [ndelvalle/v-click-outside#79]
When you try to update the version of the package, the old version is downloaded (2.1.2).

**Comment by ndelvalle** [comment]
I'm not sure I understand, there is `2.1.3` version on npm

https://www.npmjs.com/package/v-click-outside/v/2.1.3

**Comment by ndelvalle** [comment]
@ThD-Rizer any news? Can I close the issue?

**Comment by ThD-Rizer** [comment]
@ndelvalle hello. Apparently npm did not immediately update the version and downloaded from the cache. It's all right now, thanks :)
