### ISSUE TITLE
Click outside doesn't work on iframe click

### ISSUE THREAD

**Issue by kiril-malyhin** [ndelvalle/v-click-outside#80]
Unexpectedly, click on iframe doesn't fires event. Please, check this issue.

**Comment by ndelvalle** [comment]
@kiril-malyhin Can you add more details. Can you create a codesandbox like this one:

 [![Edit v-click-outside](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/zx7mx8y1ol?fontsize=14)

**Comment by kiril-malyhin** [comment]
@ndelvalle , sure.

Link to sandbox: https://codesandbox.io/s/5v256q385k?fontsize=14
As you see, event on click on iframe is not fired.

**Comment by monkeyWzr** [comment]
Hi @ndelvalle can I work on this one?
(I did some search and I think I can handle it)

**Comment by ndelvalle** [comment]
@monkeyWzr yes sure, thanks for the help 🙂

**Comment by kiril-malyhin** [comment]
@monkeyWzr , that would be great if you can handle it!

**Comment by kiril-malyhin** [comment]
@monkeyWzr , do you have any updates on this issue?

**Comment by monkeyWzr** [comment]
@kiril-malyhin Nothing at all. I'm so sorry...

**Comment by kiril-malyhin** [comment]
@monkeyWzr , probably you will can try solutions from here: https://stackoverflow.com/questions/15080222/add-click-event-to-iframe

**Comment by renatodeleao** [comment]
the `blur` solution seems to be working, from my light testing. Firefox `document.activeElement` becomes `body` instead of the actual `iframe` on (chrome, safari, edge) `window.blur`.

```js
onWindowBlur() {
  if (document.activeElement.tagName === 'IFRAME' || document.activeElement === document.body ) {
        handler()
 }
}
```

@monkeyWzr did you remember any edge case from this? Cheers ✌️
