### ISSUE TITLE
Click outside method is triggered multiple times

### ISSUE THREAD

**Issue by koraykupe** [ndelvalle/v-click-outside#82]
Hi,
I have that code on my Vue file:

```
    <li class="nav-item nav-item-dropdown" v-click-outside="hidePanel">
        <a class="nav-link" href="javascript:;" @click="showPanel">
            <slot name="link"></slot>
        </a>
        <div class="nav-item-panel" :class="{ active: panelActive }">
            <navbar>
                <button @click="hidePanel">Close</button>
            </navbar>
            <slot name="panel"></slot>
        </div>
    </li>
```
and that methods:

`  showPanel () {
        this.panelActive = true
        console.log('show panel')
        if (this.isMobileDevice) {
          document.body.className = 'body-no-scroll'
        }
      },
      hidePanel () {
        this.panelActive = false
        console.log('hide panel')
        if (this.isMobileDevice) {
          document.body.className = document.body.className.replace(
            'body-no-scroll',
            ''
          )
        }
      }`

When I click the dropdown element, I see the show panel / hide panel logs multiple times on each click. If I implement it like on the first example on the documentation (by passing a data object instead of a method) it works.

What is wrong with that code?

Btw, I test it using Chrome debugger and realised that it invokes both touchevent and click event at the same time. It may be related to that.

Best Regards

**Comment by koraykupe** [comment]
I added v-if statement to panelActive <div class="nav-item-panel"> dom element and it works now.

**Comment by ndelvalle** [comment]
@koraykupe thanks for sharing your solution.
