### ISSUE TITLE
Trigger when unmounting a component

### ISSUE THREAD

**Issue by Nberezhnoy** [ndelvalle/v-click-outside#94]
Hey. Found such an error. When switching between routes, if on the page there is one and the same element in which the property "isActive" changes in the config, then the click event is triggered when a click is inside the element that uses the directive.
When debugging, I found out that on the line [L27](https://github.com/ndelvalle/v-click-outside/blob/master/lib/v-click-outside.js#L27) there is a check of occurrence in an already unmounted element.
Solved the problem by deleting `setTimeout` when adding and removing event listeners.

Error example [https://codesandbox.io/s/v-click-outside-4b8rz](https://codesandbox.io/s/v-click-outside-4b8rz)
In the example, you need to switch between the pages of the application several times in order to reproduce the erroneous behavior

**Comment by ndelvalle** [comment]
@Nberezhnoy I check you codesanbox (Thank you very much for creating one) and I am not being able to reproduce the error, can you try again using the last `vue` and `v-click-outside` versions?

**Comment by ndelvalle** [comment]
Feel free to open this issue again if you are still having the problem.
